### ISSUE TITLE
Question 6 

### ISSUE THREAD

**Issue by basbruss** [misjamikkers/Rprogramming21_student#1]
In [https://github.com/misjamikkers/Rprogramming21_student/blob/main/Practice%20Exams/Code/Exam_questions.Rmd](url) the formula to determine variable 'y' in question 6 differs from the formula used in the answers [https://github.com/misjamikkers/Rprogramming21_student/blob/main/Practice%20Exams/Code/Exam_answers.Rmd](url).

**Comment by gsverhoeven** [comment]
Thanks for reporting. Fixed and updated repo.
